name: Mimi Launcher Android CI & Release

on:
  push:
    branches:
      - "main" # Jab bhi tum main branch par normal push karoge, release ban jayegi! 🚀

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build Launcher Debug APK
        run: ./gradlew assembleDebug

      - name: Create Artifacts Directory & Copy Files
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/*.apk artifacts/

      - name: Upload Mimi Launcher Artifacts Folder
        uses: actions/upload-artifact@v4
        with:
          name: mimi-launcher-release-apk
          path: artifacts/
          if-no-files-found: error
          retention-days: 7

      # Har normal push par apne aap unique release banana 🚀🎉
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.apk
          name: Mimi Launcher Build-${{ github.run_number }}
          tag_name: build-${{ github.run_number }}
          draft: false
          prerelease: false
